### ISSUE TITLE
panic executing saga that used `append_parallel` with empty Vec

### ISSUE THREAD

**Issue by davepacheco** [oxidecomputer/steno#25]
@jmpesp ran into a case where Steno panicked here:

```
thread 'parallel_count_from_0_to_n' panicked at 'assertion failed: `(left == right)`
  left: `4`,
 right: `3`', /home/jwm/src/oxidecomputer/steno/src/saga_[exec.rs:94](http://exec.rs:94/):13
stack backtrace:
```

We're blowing an assertion because we've successfully completed the "end_node" (which is a node that gets added after all of the user's nodes), but there's one fewer output than we expect.  Normally, every successful node has an output, and the end node depends on all previous nodes, so if it's finishing, that means all previous nodes must have succeeded and should have emitted an output.

Here was the input template:

```rust
pub async fn parallel(times: u8) -> anyhow::Result<CountingSagaBuilder> {
        let node_names: Vec<String> =
            (0..times).map(|i| format!("add{}", i)).collect();

        let mut w = SagaTemplateBuilder::new();

        w.append("init", "init", steno::new_action_noop_undo(init));
    
        w.append_parallel( 
            (0..times)                                            
                .map(|i| {
                    (                                       
                        node_names[i as usize].as_str(),
                        node_names[i as usize].as_str(),
                        ActionFunc::new_action(add, subtract),
                    )
                })
                .collect(),
        );
                     
        w.append("end", "end", steno::new_action_noop_undo(end));
            
        Ok(CountingSagaBuilder { node_names, template: Arc::new([w.build](http://w.build/)()) })
    }
```

James found that in the case that panicked, `times` was `0`.  That made this easy to reproduce.  I copied and trimmed an existing example to make this repro case:

```rust
use serde::Deserialize;
use serde::Serialize;
use slog::Drain;
use std::sync::Arc;
use steno::ActionContext;
use steno::ActionError;
use steno::SagaId;
use steno::SagaTemplate;
use steno::SagaTemplateBuilder;
use steno::SagaType;
use uuid::Uuid;

#[tokio::main]
async fn main() {
    let log = {
        let decorator = slog_term::TermDecorator::new().build();
        let drain = slog_term::FullFormat::new(decorator).build().fuse();
        let drain = slog::LevelFilter(drain, slog::Level::Warning).fuse();
        let drain = slog_async::Async::new(drain).build().fuse();
        slog::Logger::root(drain, slog::o!())
    };
    let sec = steno::sec(
        log.new(slog::o!()),
        Arc::new(steno::InMemorySecStore::new()),
    );
    let context = Arc::new(DummyContext {});
    let params = DummyParams {};

    let saga_template = Arc::new(make_saga());
    let saga_id = SagaId(Uuid::new_v4());
    let saga_future = sec
        .saga_create(
            saga_id,
            Arc::new(context),
            saga_template,
            "dummy-saga".to_string(),
            params,
        )
        .await
        .expect("failed to create saga");
    sec.saga_start(saga_id).await.expect("failed to start saga running");
    let result = saga_future.await;
    println!("{:?}", result);
}

fn make_saga() -> SagaTemplate<DummySaga> {
    let mut builder = SagaTemplateBuilder::new();

    builder.append("init", "init", steno::new_action_noop_undo(init));
    builder.append_parallel(Vec::new());
    builder.append("end", "end", steno::new_action_noop_undo(end));

    builder.build()
}

#[derive(Debug, Deserialize, Serialize)]
struct DummyParams {}
#[derive(Debug)]
struct DummyContext;

#[derive(Debug)]
struct DummySaga;
impl SagaType for DummySaga {
    type SagaParamsType = DummyParams;
    type ExecContextType = Arc<DummyContext>;
}

async fn init(_: ActionContext<DummySaga>) -> Result<(), ActionError> {
    Ok(())
}

async fn end(
    _: ActionContext<DummySaga>,
) -> Result<(), ActionError> {
    Ok(())
}
```

I put this into `examples/bug.rs` and reproduced the problem:

```
$ cargo run --example=bug
    Finished dev [unoptimized + debuginfo] target(s) in 0.08s
     Running `target/debug/examples/bug`
thread 'tokio-runtime-worker' panicked at 'assertion failed: `(left == right)`
  left: `4`,
 right: `3`', /Users/dap/oxide/steno/src/saga_exec.rs:94:13
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
thread 'main' panicked at 'failed to wait for saga to finish', src/sec.rs:996:21
```

If I comment out the `append_parallel()`, it works.

Interestingly, if I run it a few more times with the `append_parallel()`, it fails in different ways:

```
$ cargo run --example=bug
    Finished dev [unoptimized + debuginfo] target(s) in 0.07s
     Running `target/debug/examples/bug`
thread 'tokio-runtime-worker' panicked at 'called `Option::unwrap()` on a `None` value', /Users/dap/oxide/steno/src/saga_exec.rs:1215:46
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
thread 'main' panicked at 'failed to wait for saga to finish', src/sec.rs:996:21
```

```
$ cargo run --example=bug
   Compiling steno v0.1.0 (/Users/dap/oxide/steno)
    Finished dev [unoptimized + debuginfo] target(s) in 3.54s
     Running `target/debug/examples/bug`
thread 'tokio-runtime-worker' panicked at 'assertion failed: `(left == right)`
  left: `4`,
 right: `3`', /Users/dap/oxide/steno/src/saga_exec.rs:94:13
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
thread 'thread 'maintokio-runtime-worker' panicked at '' panicked at 'failed to wait for saga to finishcalled `Result::unwrap()` on an `Err` value: SendError(LogEvent(SagaLogEventData { ack_tx: Sender { inner: Some(Inner { state: State { is_complete: false, is_closed: false, is_rx_task_set: false, is_tx_task_set: false } }) }, event: N001 started }))', ', src/sec.rssrc/sec.rs::996736::2138
```

Looking at the code in `append_parallel`: I think the problem is that if you append zero nodes, we wind up (a) not adding any new nodes, but (b) replacing `self.last_nodes` with the empty Vec.  The side effect of this is that when you add the next node(s) using `append` or `append_parallel`, they will be missing a dependency on the previous nodes.  This would also be true when steno goes to add its own "end" node.  In this case, the net result is that the _user's_ "end" node does not depend on their own "init" node, and thus steno's "end" node does not wind up depending in any way on the user's "start" node.  Thus, the "end" node can wind up running and finishing before other nodes have finished and we blow the assertion.

There are a couple of possible fixes:

- make `append_parallel()` with an empty Vec a no-op: just don't do anything
- make `append_parallel()` with an empty Vec panic -- I kind of prefer this, since it seems likely to be a bug in the caller
- make `append_parallel()` with an empty Vec return an error `Result` -- this would be okay but it's a breaking change and I'm not sure what a caller would ever do with this besides unwrap it

Fortunately there's an easy workaround: don't call `append_parallel` with an empty Vec.

**Comment by davepacheco** [comment]
This will be fixed in #29 by causing the DAG build to fail if you try to do this.
